kind: pipeline
name: default

steps:
- name: unit test - api-gateway
  image: node
  commands:
    - cd api-gateway
    - npm install
    - npm run unit-test
- name: unit test - my-service
  image: node
  commands:
    - cd my-service
    - npm install
    - npm run unit-test
    