kind: secret
name: docker_test
get:
  path: secret/data/docker
  name: test
name: access_key
get:
  path: secret/data/docker
  name: access_key
name: secret_key
get:
  path: secret/data/docker
  name: secret_key
name: account_id
get:
  path: secret/data/docker
  name: account_id


kind: pipeline
name: default

steps:
- name: api-gateway - unit test
  image: node
  settings:
    testSecretValue:
      from_secret: docker_test
  commands:
    - cd api-gateway
    - npm install --unsafe-perm
    - npm run unit-test
- name: api-gateway - service level integration tests
  image: node
  commands:
    - cd api-gateway
    - npm install
    - npm run integration-test
- name: publish  
  image: plugins/ecr
  settings:
    access_key: <access_key>
    secret_key: <secret_key>
    repo: <account_id>.dkr.ecr.eu-west-1.amazonaws.com/microservice-example
    registry: <account_id>.dkr.ecr.eu-west-1.amazonaws.com
- name: my-service - unit test
  image: node
  commands:
    - cd my-service
    - npm install
    - npm run unit-test
- name: my-service - service level integration tests
  image: node
  commands:
    - cd my-service
    - npm install
    - npm run integration-test
    